apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ingress-nginx
  name: hello-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring
  template:
    metadata:
      labels:
        app: hello-spring
    spec:
      nodeSelector:
        app: hello-spring
      containers:
      - name: hello-spring
        image: dksdygks32/hello-spring:mysql
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_HOST 
          value: "hello-spring-mysql"
---
apiVersion: v1
kind: Service
metadata:
  namespace: ingress-nginx
  name: hello-spring-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: hello-spring
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ingress-nginx
  name: hello-spring-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-spring-service
            port:
              number: 8080
