apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: ingress-nginx
  labels:
    app: hello-spring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi